apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-01
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-test-01
  nfs:
    server: 192.168.139.161
    path: /tmp/k8s-pv
